# admin/config.yml
backend:
  name: git-gateway
  repo: arjun-tarakesh/potfolio
  branch: main


media_folder: "assets/img/uploads"
public_folder: "/assets/img/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - label: "Categories"
        name: "categories"
        widget: "list"
        default: ["Blogging"]
      - { label: "Published", name: "published", widget: "boolean", default: true }
      - { label: "Body", name: "body", widget: "markdown" }
      
    # 🔽 Toggle for enabling an image
      - label: "Include Image"
        name: "hasImage"
        widget: "boolean"
        default: false
        required: false

    # 🔽 Image upload field (conditional)
      - label: "Cover Image"
        name: "image"
        widget: "image"
        required: false
        hint: "Shown only if 'Include Image' is toggled"
        conditional:
          field: "hasImage"
          value: true
