# admin/config.yml
backend:
  name: git-gateway
  repo: arjun-tarakesh/potfolio
  branch: main


media_folder: "assets/img/uploads"
public_folder: "/assets/img/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Excerpt", name: "excerpt", widget: "string", required: false }
      - label: "Category"
        name: "categories"
        widget: "list"
        allow_add: true
        default: ["general"]
        required: false
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Cover Image", name: "image", widget: "image", required: false, default: "" }


